services:
    db:
        image: postgres:16
        environment:
            POSTGRES_USER: agqe_user
            POSTGRES_PASSWORD: agqe_password
            POSTGRES_DB: agqe_db
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: