import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"], // You can adjust weights as needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="description" content="Site da ONG A.G.Q.E (Agência e Grupo Quatro Estações)" />
      <meta name="keywords" content="apoio lgbt, lgbtqia+, ong, agqe, são joão da boa vista, direitos humanos, diversidade" />
      <meta name="author" content="Luis Felipe Colosimo & Henrique Bissoli Malaman Alonso" />
      <body
        className={`${roboto.variable} antialiased bg-zinc-100 text-zinc-800`}

        cz-shortcut-listen="true"
      >
        {children}
      </body>
    </html>
  );
}
