import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Associação e Grupo Quatro Estações - AGQE",
  description: "Generated by create next app",
  icons: {
    icon: ""
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content="Site da ONG A.G.Q.E (Agência e Grupo Quatro Estações)" />
        <meta name="keywords" content="apoio lgbt, lgbtqia+, ong, agqe, são joão da boa vista, direitos humanos, diversidade" />
        <meta name="author" content="Luis Felipe Colosimo & Henrique Bissoli Malaman Alonso" />
        <meta name="author" content="aplicação em NextJS desenvolvida por Felipe Kafka Dias" />
        <title>AGQE - Associação e Grupo Quatro Estações</title>
      </head>
      <body
        className={`${roboto.variable} antialiased bg-zinc-100 text-zinc-800`}

        cz-shortcut-listen="true"
      >
        {children}
      </body>
    </html>
  );
}
